/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes";
import type { FormIdentifier } from "sap/fe/test/api/FormAPI";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("SpacefarersObjectPageObjectPage journey");

    opaTest("Navigate to SpacefarersObjectPageObjectPage", function (Given: Given, When: When, Then: Then) {
        Given.iStartMyApp();

        When.onTheSpacefarersListGenerated.onFilterBar().iExecuteSearch();

        Then.onTheSpacefarersListGenerated.onTable("").iCheckRows();
        When.onTheSpacefarersListGenerated.onTable("").iPressRow(0);

        Then.onTheSpacefarersObjectPageGenerated.iSeeThisPage();
    });



    opaTest("Check body sections of the Object Page", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheSpacefarersObjectPageGenerated.iCheckSection({ section: "GeneralInformation" }, {});
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "firstName" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "lastName" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "email" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "originPlanet" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "spacesuitColor" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "stardustCollection" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "wormholeNavigationSkill" });
        Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInformation" } as unknown as FormIdentifier).iCheckField({ property: "position_ID" });
   });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
